apiVersion: v1
kind: Pod
metadata:
  name: terraform-nginx 
  labels:
    app: kubetest 
  annotations:
    name: kubernetes 
  namespace: default
spec:
  containers:
  - name: terraform-nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  
  - name: terraform-ubuntu 
    image: ubuntu:latest
    command:
      - "sleep"
      - "1000"