---
- name: "Creating pod using ansible"
  hosts: localhost
  become: true
  vars:
    - kubeconfig_file: "/home/haruna/.kube/config"
    - ansible_python_interpreter: "/usr/bin/python3"
    - ansible_connection: local
    - ansible_sudo_pass: haroun
  tasks:
    - name: "Create deployment"
      k8s:
        kubeconfig: "/home/haruna/.kube/config"
        src: main.yml
        state: present 
